### ISSUE TITLE
New Bitcoin address ?

### ISSUE THREAD

**Issue by Bitaltyn-project** [1btcxe/wlox-frontend#84]
Why not create a new Bitcoin add
![bitcoin](https://cloud.githubusercontent.com/assets/15166908/10791866/8d89f1e2-7db4-11e5-92ec-6e40a91f5862.png)
ress ?

**Comment by mbassan** [comment]
Which one are you asking?

1) Why doesn't creating a new bitcoin address work?
2) Why doesn't it create a new address every time you access deposit.php?

Please clarify.

On Wed, Oct 28, 2015 at 9:43 AM, Bitaltyn-project notifications@github.com
wrote:

> Why not create a new Bitcoin add
> [image: bitcoin]
> https://cloud.githubusercontent.com/assets/15166908/10791866/8d89f1e2-7db4-11e5-92ec-6e40a91f5862.png
> ress ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/1btcxe/wlox-frontend/issues/84.

## 

Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by Bitaltyn-project** [comment]
Why did he not created when registering or manage bitcoin adresses?

**Comment by mbassan** [comment]
Because your wlox-api library is not connecting to the bitcoind instance.
Check your settings in backstage2 -> status -> app_config under Bitcoind
Settings.

Also, check your bitcoin.conf setup to make sure it allows http connections
and allows the IP of your wlox-api and wlox-cron instances.

On Wed, Oct 28, 2015 at 11:37 AM, Bitaltyn-project <notifications@github.com

> wrote:
> 
> Why did he not created when registering or manage bitcoin adresses?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/1btcxe/wlox-frontend/issues/84#issuecomment-151903330
> .

## 

Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by ergofobe** [comment]
This is a wlox deployment issue, not a 1btcxe issue. Also, I think it has been sufficiently answered by @mbassan so I'm closing it rather than creating a new issue in wlox.
